### ISSUE TITLE
[Epic] Issues affecting small groups of packages

### ISSUE THREAD

**Issue by dhodovsk** [packit/dist-git-to-source-git#56]
Since most of the issues are on this repository already, I added this issue here so we don't have to track it somewhere else. Many of the issues might be resolved directly in the package.

- [ ] Doing readlink in patch for cycle returns weird patch name (`pipe:[2248369]`)
  -  because of that packit srpm fails with `.patch: No such file or directory`
  - packages - `authselect`, `sssd`
- [ ] patch defined but not applied
  - because of that packit srpm fails again, with `.patch: No such file or directory`
  - packages - `dovecot`, `qt5-qtbase`, `sed`
- [ ] autosetup macro defined twice in prep
  - because of that packit srpm fails `error: patch 1 defined multiple times`
  - package - `ksh`
- [ ] fg: no job control
  - package: `ongres-scram`, `prometheus-jmx-exporter`
- [ ] needs gtkdocize (not in centos?)
  - `yum whatprovides gtkdocize` in dist2src container returns no matches
  - package: `orc`
- [ ] error: possibly undefined macro
  - `expat` - AC_PROG_LIBTOOL, AC_LIBTOOL_WIN32_DLL
  - `gvfs` - AM_PATH_LIBGCRYPT

**Comment by TomasTomecek** [comment]
> error: HAVE_INTROSPECTION does not appear in AM_CONDITIONAL'

I found that we need `gtk-doc` for this, which is not yet present in the public repos

**Comment by TomasTomecek** [comment]
> python-rpm-generators

there is no tarball, lol :D

```
Source0:        https://raw.githubusercontent.com/rpm-software-management/rpm/102eab50b3d0d6546dfe082eac0ade21e6b3dbf1/COPYING                                                                
Source1:        python.attr                                                                                                                                                                   
Source2:        pythondeps.sh                                                                                                                                                                 
Source3:        pythondistdeps.py   
```

```
%prep                                                                                                                                                                                         
%autosetup -c -T                                                                                                                                                                              
cp -a %{sources} .                                                                                                                                                                            
                                                                                                                                                                                              
# Set which Python versions should have the major-version provides                                                                                                                            
# (pythonXdist...) generated                                                                                                                                                                  
sed -i 's/@MAJORVER-PROVIDES-VERSIONS@/2.7,3.6/' python.attr                                                                                                                                  
```

**Comment by dhodovsk** [comment]
`polkit-gnome` needs gnome-common, glib2-devel and intltool and then anyway fails with
```
cmdline: git cherry-pick --keep-redundant-commits --strategy-option=theirs updates~7
  stderr: 'error: could not resolve HEAD commit
```
